### ISSUE TITLE
Unable to read external constants file after upgrading nightwatch to 1.0+

### ISSUE THREAD

**Issue by jtheodore-rent** [TestArmada/magellan#274]
I'm working on upgrading nightwatch to 1.2.4 - we have been using 0.9.21 without issue for a while now but would like to get up to date with the latest version of nightwatch.

For some reason, after the update, magellan is throwing an error when I have an external constants file defined.

I am using the local executor to run tests against Saucelabs because we need to define options in desiredCapabilities that are unavailable in Guacamole.

The error output is below:

```12:26:41 =====> Magellan child process start
12:26:41    Error: An error occurred while trying to start the Nightwatch Runner: Error reading external global file using "./lib/globals.js"
12:26:41    Error: Cannot find module '/Users/jtheodore/source/rent-js/temp/build-magellan-1fe93ce8b41e83_1ea5c1c8615887__temp_assets/lib/globals.js'
12:26:41   Require stack:
12:26:41   - /Users/jtheodore/source/rent-js/node_modules/nightwatch/lib/testsuite/context.js
12:26:41   - /Users/jtheodore/source/rent-js/node_modules/nightwatch/lib/settings/globals.js
12:26:41   - /Users/jtheodore/source/rent-js/node_modules/nightwatch/lib/runner/cli/cli.js
12:26:41   - /Users/jtheodore/source/rent-js/node_modules/nightwatch/lib/index.js
12:26:41   - /Users/jtheodore/source/rent-js/node_modules/nightwatch/bin/runner.js
12:26:41   - /Users/jtheodore/source/rent-js/node_modules/nightwatch/bin/nightwatch
12:26:41        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
12:26:41        at Function.Module._load (internal/modules/cjs/loader.js:687:27)
12:26:41        at Module.require (internal/modules/cjs/loader.js:849:19)
12:26:41        at require (internal/modules/cjs/helpers.js:74:18)```

**Comment by Rama1107** [comment]
has somebody finded the desicison?
